### ISSUE TITLE
解析邮件出现部分乱码

### ISSUE THREAD

**Issue by yutent** [nodemailer/mailparser#173]
如图，标题和from中的中文，部分出现乱码。
![image](https://cloud.githubusercontent.com/assets/11972650/21801543/038189e8-d75d-11e6-9240-c6cdf722d9fd.png)

而用Imap.parseHeader解析，是正常的
![image](https://cloud.githubusercontent.com/assets/11972650/21801561/1b721ed2-d75d-11e6-88d6-7590bebdaa25.png)

**Comment by andris9** [comment]
I would need an example rfc822 message that is garbled up by mailparser like this.

**Comment by yutent** [comment]
Thanks for answering, here the email that is garbled.
[email.eml.zip](https://github.com/andris9/mailparser/files/697955/email.eml.zip)

**Comment by andris9** [comment]
The email subject is composed invalidly, it uses a base64 string that is split between a codepoint sequence. Parsing works in the IMAP parseHeader because the imap module concatenates the base64 chunks before decoding. This behavior is not allowed by the standards but it happens a lot, so mail handlers usually are able to process these values.

Actually I have fixed this in my other email libraries that handle encoded-words like the imap module but I have not fixed it in Mailparser which is quite old. I haven't had time to upgrade it to use the newer mime handling functions yet.

* This is the updated and working method: [decodeWords() in libmime](https://github.com/nodemailer/libmime/blob/d9be88efc962ba0d43149e9a03605e15721cea8c/lib/libmime.js#L254-L289)
* This is the method that is used by Mailparser and does not handle invalid base64 sequences: [decodeMimeWords() in mimelib](https://github.com/andris9/mimelib/blob/master/lib/mimelib.js#L340-L365).

For now I don't know when I have time to upgrade Mailparser to the newer mime functions.
