### ISSUE TITLE
Can't resolve 'fs' in '.../node_modules/html-to-text/lib'

### ISSUE THREAD

**Issue by barrymichaeldoyle** [nodemailer/mailparser#191]
After added this `mailparser` package to my project I get the following error:

> Error: Can't resolve 'fs' in '{projectPath}/node_modules/html-to-text/lib'

I've been trying various fixes but one fix just leads to another. How do I get around this issue?

**Comment by markin-io** [comment]
@barrymichaeldoyle I suppose you're trying use mailparser in the browser application. I faced the same issue. If you're using webpack, It may be fixed by adding `node: {    fs: 'empty' } ` into your webpack config. Sadly it turned out that mailparser is extremely slow in the browser. For example it parses 6.5mb email for 269ms in Node and 10sec in a browser.

**Comment by rohitsud** [comment]
I agree with @markin-io that Mailparser is slow in browser. In fact, it simply failed to render an email in IE while on Chrome/FF the performance was of the order of seconds to parse a simple email.
