### ISSUE TITLE
How the parse the Replied message i receive and segregate properly

### ISSUE THREAD

**Issue by chetanpatel6** [nodemailer/mailparser#267]
text: 'okay cool.\n' +
        '\n' +
        'On Tue, 7 Jul 2020 at 13:27, <chetanpatel***@*******.com> wrote:\n' +
        '\n' +
        '> Hi chetan patel,\n' +
        '> Thank you for your email. We would love to help solve your issue.\n' +
        '> We will get back to you in 2 days i.e., (Thu Jul 09 2020).\n' +
        '>\n'

This is the Replied Text i got.
Now i want to segregate it such that
 'okay cool.\n'  in different variable.

And the Replied to message in different variable,i.e.,
'> Hi chetan patel,\n' +
        '> Thank you for your email. We would love to help solve your issue.\n' +
        '> We will get back to you in 2 days i.e., (Thu Jul 09 2020).\n' +
        '>\n'

**Comment by eBulldog** [comment]
I would suggest this is beyond the scope of mailparser, and certainly isn't an 'issue'. Your question is probably better answered elsewhere, e.g. a quick google of "how to split strings/text in javascript" will give you some options. I would also advise that the structure you've shown is dependent on email client used, for example some clients default to the reply being below the original message rather than above as you've shown here (therefore your code would need to be able to deal with that).
