### ISSUE TITLE
bug: vulnerable to regex bomb attack from twitter regex

### ISSUE THREAD

**Issue by titanism** [nodemailer/mailparser#378]
The regex here is vulnerable to Regex DDOS (regex bomb) attack which will cause 100% CPU.

<https://github.com/nodemailer/mailparser/blob/af0c1e6044643ee9c9590e3bac5ceaac2c5120a4/lib/mail-parser.js#L32>

**Comment by andris9** [comment]
Pretty much all complex regexes are vulnerable to ReDos. I’ve migrated some more important ones to use a token parsing approach instead of regexes but this requires a lot of work. Other than that, I guess, do not parse emails from untrusted sources with this linrary. There’s no way I’m able to fix all the ReDos issues 🤷‍♂️

**Comment by andris9** [comment]
Re2 does not support lookaheads so it is a no go.
